version: '3.8'

services:
  lecai-app:
    build: .
    container_name: lecai
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./static/uploads:/app/static/uploads
      - ./static/results:/app/static/results
      - ./static/docs:/app/static/docs
    restart: always